from setuptools import setup, find_packages

setup(
    name="ai-content-automation",
    version="0.1.0",
    description="Generated by AppCraft v2",
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=[
        # Dependencies will be loaded from requirements.txt
    ],
    entry_points={
        "console_scripts": [
            # Add CLI scripts here
        ]
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)
