version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ai_content
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  scraper:
    build: 
      context: .
      dockerfile: services/scraper/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres:5432/ai_content
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  summarizer:
    build:
      context: .
      dockerfile: services/summarizer/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres:5432/ai_content
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres
      - redis

  publisher:
    build:
      context: .
      dockerfile: services/publisher/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres:5432/ai_content
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  dashboard:
    build:
      context: .
      dockerfile: services/dashboard/Dockerfile
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres:5432/ai_content
      - SCRAPER_URL=http://scraper:8001
      - SUMMARIZER_URL=http://summarizer:8002
      - PUBLISHER_URL=http://publisher:8003
    depends_on:
      - postgres
      - scraper
      - summarizer
      - publisher

volumes:
  postgres_data: